namespace Employee_Assignment
{
    internal class Program
    {
        static void Main()
        {

        }
    }


    public class Employee
    {
        private string name;
        private int empNo;  // must be readonly and autogenerated
        private decimal basic; //must be between some range
        private short deptNo;

        public string Name
        {
            set
            {
                if (value != null)
                    name = value;
                else
                    Console.WriteLine("invalid input");
            }
            get
            {
                return name;
            }

        }
    }
}